apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-job
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: todo-job
            image: brianlin24/todo-job
            imagePullPolicy: Always
          restartPolicy: OnFailure
