apiVersion: v1
kind: Service
metadata:
  name: todo-server-svc
spec:
  type: ClusterIP
  selector:
    app: todo-server
  ports:
    - name: server
      port: 3000
      targetPort: 8000
    - name: backend
      port: 3001
      targetPort: 8001
