apiVersion: v1
kind: Service
metadata:
  name: exercise-1-11-svc
spec:
  type: ClusterIP
  selector:
    app: exercise-1-11
  ports:
    - name: ping-pong
      port: 3000
      targetPort: 8000
    
    - name: log-output
      port: 3001
      targetPort: 8001
