apiVersion: apps/v1
kind: Deployment
metadata:
  name: rand-string
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rand-string
  template:
    metadata:
      labels:
        app: rand-string
    spec:
      containers:
        - name: rand-string
          image: brianlin24/rand-string:v1
