apiVersion: v1
kind: Service
metadata:
  name: todo-server-svc
spec:
  type: NodePort
  selector:
    app: todo-server
  ports:
    - nodePort: 30080
      protocol: TCP
      port: 3000
      targetPort: 8000
