apiVersion: v1
kind: Service
metadata:
  name: ping-log-svc
spec:
  type: ClusterIP
  selector:
    app: ping-log
  ports:
    - name: ping-pong
      port: 3000
      targetPort: 8000
    
    - name: log-output
      port: 3001
      targetPort: 8001
